# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QT/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 796)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelPTTPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPTTPassword.setGeometry(QtCore.QRect(10, 110, 71, 31))
        self.labelPTTPassword.setObjectName("labelPTTPassword")
        self.inputPTTPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPTTPassword.setGeometry(QtCore.QRect(90, 110, 201, 31))
        self.inputPTTPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.inputPTTPassword.setText("")
        self.inputPTTPassword.setMaxLength(32767)
        self.inputPTTPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPTTPassword.setObjectName("inputPTTPassword")
        self.inputPTTAID = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPTTAID.setGeometry(QtCore.QRect(90, 200, 201, 31))
        self.inputPTTAID.setText("")
        self.inputPTTAID.setObjectName("inputPTTAID")
        self.inputPTTID = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPTTID.setGeometry(QtCore.QRect(90, 59, 201, 31))
        self.inputPTTID.setText("")
        self.inputPTTID.setObjectName("inputPTTID")
        self.labelPTTPassword_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelPTTPassword_2.setGeometry(QtCore.QRect(10, 200, 71, 31))
        self.labelPTTPassword_2.setObjectName("labelPTTPassword_2")
        self.labelPTTID = QtWidgets.QLabel(self.centralwidget)
        self.labelPTTID.setGeometry(QtCore.QRect(20, 60, 71, 31))
        self.labelPTTID.setObjectName("labelPTTID")
        self.bottonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.bottonLogin.setGeometry(QtCore.QRect(100, 160, 91, 31))
        self.bottonLogin.setObjectName("bottonLogin")
        self.bottonLoadPosts = QtWidgets.QPushButton(self.centralwidget)
        self.bottonLoadPosts.setGeometry(QtCore.QRect(100, 240, 91, 41))
        self.bottonLoadPosts.setObjectName("bottonLoadPosts")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(300, 10, 262, 119))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textArticleTitle = QtWidgets.QTextBrowser(self.widget)
        self.textArticleTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textArticleTitle.setFont(font)
        self.textArticleTitle.setObjectName("textArticleTitle")
        self.verticalLayout_3.addWidget(self.textArticleTitle)
        self.scrollPost = QtWidgets.QScrollArea(self.widget)
        self.scrollPost.setWidgetResizable(True)
        self.scrollPost.setObjectName("scrollPost")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 254, 60))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollPost.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollPost)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPTTPassword.setText(_translate("MainWindow", "輸入PTT 密碼 :"))
        self.inputPTTPassword.setPlaceholderText(_translate("MainWindow", "PTT 密碼"))
        self.inputPTTAID.setPlaceholderText(_translate("MainWindow", "#1VyG2jpG (C_Chat)"))
        self.inputPTTID.setPlaceholderText(_translate("MainWindow", "PTT ID"))
        self.labelPTTPassword_2.setText(_translate("MainWindow", "輸入文章代碼 :"))
        self.labelPTTID.setText(_translate("MainWindow", "輸入PTT ID :"))
        self.bottonLogin.setText(_translate("MainWindow", "登入PTT"))
        self.bottonLoadPosts.setText(_translate("MainWindow", "讀取推文"))
        self.textArticleTitle.setPlaceholderText(_translate("MainWindow", "文章標題"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
