# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QT/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 897)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelPTTPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPTTPassword.setGeometry(QtCore.QRect(0, 110, 131, 31))
        self.labelPTTPassword.setObjectName("labelPTTPassword")
        self.inputPTTID = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPTTID.setGeometry(QtCore.QRect(140, 59, 201, 31))
        self.inputPTTID.setText("")
        self.inputPTTID.setObjectName("inputPTTID")
        self.labelAID = QtWidgets.QLabel(self.centralwidget)
        self.labelAID.setGeometry(QtCore.QRect(0, 200, 131, 31))
        self.labelAID.setObjectName("labelAID")
        self.labelPTTID = QtWidgets.QLabel(self.centralwidget)
        self.labelPTTID.setGeometry(QtCore.QRect(0, 60, 131, 31))
        self.labelPTTID.setObjectName("labelPTTID")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 10, 21, 801))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.inputPTTPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPTTPassword.setGeometry(QtCore.QRect(140, 110, 201, 31))
        self.inputPTTPassword.setText("")
        self.inputPTTPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPTTPassword.setObjectName("inputPTTPassword")
        self.inputPTTAID = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPTTAID.setGeometry(QtCore.QRect(140, 200, 201, 31))
        self.inputPTTAID.setText("")
        self.inputPTTAID.setObjectName("inputPTTAID")
        self.bottonLoadPosts = QtWidgets.QPushButton(self.centralwidget)
        self.bottonLoadPosts.setGeometry(QtCore.QRect(170, 240, 91, 31))
        self.bottonLoadPosts.setObjectName("bottonLoadPosts")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 10, 761, 861))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textArticleTitle = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textArticleTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textArticleTitle.setFont(font)
        self.textArticleTitle.setObjectName("textArticleTitle")
        self.verticalLayout_3.addWidget(self.textArticleTitle)
        self.scrollPost = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollPost.setWidgetResizable(True)
        self.scrollPost.setObjectName("scrollPost")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 753, 802))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollPost.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollPost)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPTTPassword.setText(_translate("MainWindow", "輸入PTT 密碼 :"))
        self.inputPTTID.setPlaceholderText(_translate("MainWindow", "PTT ID"))
        self.labelAID.setText(_translate("MainWindow", "輸入文章代碼 :"))
        self.labelPTTID.setText(_translate("MainWindow", "輸入PTT ID :"))
        self.inputPTTPassword.setPlaceholderText(_translate("MainWindow", "PTT 密碼"))
        self.inputPTTAID.setPlaceholderText(_translate("MainWindow", "#1VyG2jpG (C_Chat)"))
        self.bottonLoadPosts.setText(_translate("MainWindow", "載入推文"))
        self.textArticleTitle.setPlaceholderText(_translate("MainWindow", "文章標題"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
